name: Reusable Unit Tests

on: [ workflow_call ]

jobs:
  baseUnitTest:
    name: Gradle 8.5 @ ubuntu-latest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: "8.5"
      os: ubuntu-latest

  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs: baseUnitTest
    uses: ./.github/workflows/reusable-single-unitTest.yml
    with:
      gradleVersion: ${{ matrix.gradleVersion }}
      os: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "7.6"
          - "8.5"
          - "8.6-rc-1"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: ubuntu-latest
            gradleVersion: "8.5"
